"""
Agent 13 — Packaging & Export Agent
────────────────────────────────────
Final step of every pipeline run. Bundles all generated outputs into a
ready-to-run artifact the developer can immediately use:

  localhost  → ZIP archive  +  start.sh / stop.sh  +  Electron DMG scaffold
  gcp/aws/azure → ZIP with Terraform + CI/CD ready for `terraform apply`

No Claude API call needed — this agent is pure Python file I/O.
Model tier: haiku (but actually makes zero Claude calls)
"""
from __future__ import annotations

import json
import os
import shutil
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Optional

from loguru import logger

from agents.base_agent import BaseAgent
from models.pipeline_state import PipelineState
from utils.file_utils import outputs_path, project_outputs_root, save_json, timestamped_name


class PackagingAgent(BaseAgent):
    agent_id          = "agent_13_packaging"
    name              = "Packaging & Export Agent"
    description       = "Bundles all outputs into a runnable artifact — ZIP + start script (localhost) or deployment-ready archive (cloud)"
    model_tier        = "haiku"
    max_output_tokens = 1024   # not used — this agent makes no Claude calls

    def run(self, state: PipelineState) -> PipelineState:
        project   = state.project_name
        cloud     = state.cloud_provider or "localhost"
        root      = project_outputs_root()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        self.log(f"Packaging '{project}' for {cloud}…")

        # ── 1. Write a unified start script at the project root ───────────────
        if cloud == "localhost":
            self._write_localhost_scripts(root, project)

        # ── 2. Write a manifest JSON listing every output file ────────────────
        manifest = self._build_manifest(root, project, cloud, timestamp)
        manifest_path = save_json(manifest, ".", timestamped_name("package_manifest", "json"))
        self.log(f"Manifest: {len(manifest['files'])} files listed")

        # ── 3. Create ZIP archive ─────────────────────────────────────────────
        zip_name = f"{project}_{cloud}_{timestamp}.zip"
        zip_path = root / zip_name
        file_count = self._create_zip(root, zip_path)
        self.log(f"ZIP created: {zip_name} ({file_count} files, {self._human_size(zip_path.stat().st_size)})")

        # ── 4. For localhost: write Electron desktop-app scaffold pointer ─────
        readme_path: Optional[Path] = None
        if cloud == "localhost":
            readme_path = self._write_launch_readme(root, project, zip_name)

        state.package_manifest = manifest
        self.last_summary = (
            f"Packaged {file_count} files → {zip_name}"
            + (" + start.sh" if cloud == "localhost" else "")
        )
        self.last_output_path = str(zip_path)
        return state

    # ── Localhost scripts ─────────────────────────────────────────────────────

    def _write_localhost_scripts(self, root: Path, project: str) -> None:
        """Write start.sh / stop.sh at the project output root."""
        start = root / "START.sh"
        stop  = root / "STOP.sh"

        start.write_text(f"""#!/usr/bin/env bash
# ════════════════════════════════════════════════════════
#  {project} — generated by SDLC Pipeline
#  Starts all services defined in deployments/docker-compose.yml
# ════════════════════════════════════════════════════════
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

echo "🚀  Starting {project}…"

if [[ ! -f "$SCRIPT_DIR/deployments/docker-compose.yml" ]]; then
  echo "❌  docker-compose.yml not found in deployments/"
  exit 1
fi

cd "$SCRIPT_DIR/deployments"

# Copy .env if missing
if [[ ! -f ".env" ]] && [[ -f ".env.example" ]]; then
  cp .env.example .env
  echo "⚠  Copied .env.example → .env  (review before production use)"
fi

docker compose up -d --build
echo ""
echo "✅  {project} is running!"
echo "   App:     http://localhost:3000"
echo "   API:     http://localhost:8000"
echo "   pgAdmin: http://localhost:5050"
echo ""
echo "   Run ./STOP.sh to shut everything down."
""", encoding="utf-8")

        stop.write_text(f"""#!/usr/bin/env bash
# Stops all {project} services
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
cd "$SCRIPT_DIR/deployments"
echo "⏹  Stopping {project}…"
docker compose down
echo "✅  All services stopped."
""", encoding="utf-8")

        start.chmod(0o755)
        stop.chmod(0o755)
        self.log("Wrote START.sh and STOP.sh")

    # ── Launch README ─────────────────────────────────────────────────────────

    def _write_launch_readme(self, root: Path, project: str, zip_name: str) -> Path:
        path = root / "HOW_TO_RUN.md"
        path.write_text(f"""# How to Run — {project}

Generated by SDLC Pipeline · {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## Option A — Docker Compose (quickest)

**Prerequisites:** Docker Desktop running

```bash
# 1. Start everything
./START.sh

# 2. Open the app
open http://localhost:3000

# 3. Stop when done
./STOP.sh
```

---

## Option B — Desktop App (DMG)

A native macOS wrapper is available in the `desktop-app/` folder of the pipeline repo.

```bash
cd /path/to/sdlc-agent-pipeline/desktop-app
./build.sh          # requires Node.js 18+
# → dist/SDLC Pipeline-1.0.0-arm64.dmg
```

Double-click the DMG, drag to Applications, and launch like any Mac app.

---

## What's in the ZIP — `{zip_name}`

| Folder | Contents |
|--------|----------|
| `requirements/` | PRD, gap analysis, priorities |
| `architecture/` | HLD, LLD, SQL schema, OpenAPI spec |
| `security/`     | Threat model, OWASP report |
| `code/`         | Backend (FastAPI) + Frontend (React/TS) |
| `tests/`        | Unit, integration, E2E, load tests |
| `docs/`         | README, API reference, developer guide |
| `deployments/`  | docker-compose.yml, .env.example, scripts |

---

## Folder Structure (code)

```
code/
├── src/            ← FastAPI backend
│   ├── main.py
│   ├── models/
│   ├── routers/
│   └── services/
└── frontend/       ← React + TypeScript SPA
    ├── src/
    ├── package.json
    └── vite.config.ts
```
""", encoding="utf-8")
        return path

    # ── ZIP builder ───────────────────────────────────────────────────────────

    def _create_zip(self, root: Path, zip_path: Path) -> int:
        """Zip every file under root except the zip itself and uploads/."""
        count = 0
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
            for fp in sorted(root.rglob("*")):
                if fp == zip_path:
                    continue
                if any(part in {"uploads", "__pycache__", ".git", "node_modules"}
                       for part in fp.parts):
                    continue
                if fp.suffix in {".pyc", ".pyo"}:
                    continue
                if fp.is_file():
                    arcname = fp.relative_to(root)
                    zf.write(fp, arcname)
                    count += 1
        return count

    # ── Manifest ──────────────────────────────────────────────────────────────

    def _build_manifest(self, root: Path, project: str, cloud: str, timestamp: str) -> dict:
        files = []
        total_bytes = 0
        for fp in sorted(root.rglob("*")):
            if fp.is_file() and not any(
                p in {"uploads", "__pycache__", ".git", "node_modules"} for p in fp.parts
            ) and fp.suffix not in {".pyc", ".pyo"}:
                size = fp.stat().st_size
                total_bytes += size
                files.append({
                    "path":  str(fp.relative_to(root)),
                    "size":  size,
                    "ext":   fp.suffix.lstrip(".") or fp.name,
                })
        return {
            "project":    project,
            "cloud":      cloud,
            "timestamp":  timestamp,
            "total_files": len(files),
            "total_size":  total_bytes,
            "total_size_human": self._human_size(total_bytes),
            "files":      files,
        }

    @staticmethod
    def _human_size(n: int) -> str:
        for unit in ["B", "KB", "MB", "GB"]:
            if n < 1024:
                return f"{n:.1f} {unit}"
            n /= 1024
        return f"{n:.1f} TB"
