"""Agent 12 — Frontend Generation (React + TypeScript SPA)"""
from __future__ import annotations
from pathlib import Path
from agents.base_agent import BaseAgent
from models.pipeline_state import PipelineState
from utils.file_utils import outputs_path
from utils.chunker import truncate


PAGES_SYSTEM = """
You are the Frontend Agent. Generate a complete React 18 + TypeScript SPA that connects
to the FastAPI backend generated by the previous agents.

Files to generate:

=== FILE: frontend/package.json ===
(React 18, TypeScript, react-router-dom v6, axios, @tanstack/react-query, tailwindcss, lucide-react, react-hot-toast)

=== FILE: frontend/tsconfig.json ===
(strict mode, paths alias @/ → src/)

=== FILE: frontend/vite.config.ts ===
(vite, @vitejs/plugin-react, proxy /api → http://localhost:8000)

=== FILE: frontend/tailwind.config.js ===
(content: src/**/*.{ts,tsx})

=== FILE: frontend/index.html ===
(root div, loads main.tsx)

=== FILE: frontend/src/main.tsx ===
(ReactDOM.createRoot, BrowserRouter, QueryClientProvider, Toaster)

=== FILE: frontend/src/App.tsx ===
(Route definitions: login, register, dashboard, main entity pages)

=== FILE: frontend/src/api/client.ts ===
(axios instance: baseURL from VITE_API_URL env var, interceptor to attach Bearer token from localStorage)

=== FILE: frontend/src/api/types.ts ===
(TypeScript interfaces matching the backend Pydantic schemas)

=== FILE: frontend/src/api/hooks.ts ===
(React Query hooks: useQuery + useMutation for each main entity — list, get, create, update, delete)

=== FILE: frontend/src/contexts/AuthContext.tsx ===
(login(), logout(), register(), token stored in localStorage, useAuth() hook)

=== FILE: frontend/src/pages/LoginPage.tsx ===
(email+password form, calls /api/v1/auth/login, stores token, redirects to dashboard)

=== FILE: frontend/src/pages/RegisterPage.tsx ===
(name+email+password form, calls /api/v1/auth/register)

=== FILE: frontend/src/pages/DashboardPage.tsx ===
(overview stats cards, recent items, quick actions)

=== FILE: frontend/src/pages/MainEntityPage.tsx ===
(list with search, filter, pagination; create/edit modal; delete with confirm)

=== FILE: frontend/src/components/Layout.tsx ===
(sidebar navigation, header with user avatar, logout, mobile-responsive)

=== FILE: frontend/src/components/Modal.tsx ===
(reusable modal with backdrop, close on Escape)

=== FILE: frontend/src/components/Table.tsx ===
(sortable, paginated table component)

=== FILE: frontend/src/components/Form.tsx ===
(reusable form field components: Input, Select, Textarea, Checkbox)

=== FILE: frontend/Dockerfile ===
(multi-stage: node:20-alpine build → nginx:alpine serve; nginx config to proxy /api)

=== FILE: frontend/.env.example ===
(VITE_API_URL=http://localhost:8000)

Return ONLY the files in this exact format. No JSON wrapper, no extra commentary.
Make the UI professional, clean, fully functional with real API calls to the backend.
"""

DOCKER_COMPOSE_PATCH_SYSTEM = """
You are the Frontend Agent. Given the existing docker-compose.yml below, output an
UPDATED docker-compose.yml that adds a `frontend` service:

- build: ./frontend
- ports: "3000:80"
- depends_on: [app]  (or whatever the API service is named)
- environment: VITE_API_URL=http://app:8000

Return ONLY:

=== FILE: docker-compose.yml ===
<full updated docker-compose.yml content>
"""


class FrontendAgent(BaseAgent):
    agent_id    = "agent_12_frontend"
    name        = "Frontend Agent"
    model_tier        = "sonnet"
    max_output_tokens = 8192
    description = "React 18 + TypeScript SPA — complete UI for the generated backend"

    def run(self, state: PipelineState) -> PipelineState:
        # Gather context
        openapi = state.openapi_spec or ""
        if not openapi:
            openapi = self._read_latest_output("architecture", "openapi_*.yaml") or \
                      self._read_latest_output("architecture", "openapi_*.yml")

        prd = state.prd_document or self._read_latest_output("requirements", "PRD_*.md")

        self.log("Generating React + TypeScript frontend (1/2)")

        ctx = f"""
Project: {state.project_name}

--- PRD SUMMARY ---
{truncate(prd or "", 1_500, label="PRD")}

--- OPENAPI SPEC (excerpt) ---
{truncate(openapi or "", 3_000, label="OpenAPI")}
"""

        # ── Call 1: React SPA files ────────────────────────────────────────────
        all_files = self._generate_delimited_files(PAGES_SYSTEM, ctx)

        base = outputs_path("code", "")
        written = 0
        for rel_path, content in all_files.items():
            try:
                fp = base / rel_path
                fp.parent.mkdir(parents=True, exist_ok=True)
                fp.write_text(content, encoding="utf-8")
                written += 1
            except Exception as exc:
                self.log(f"Warning: could not write {rel_path}: {exc}")

        # ── Call 2: Patch docker-compose to include frontend ───────────────────
        self.log("Updating docker-compose.yml to include frontend service (2/2)")
        existing_compose = ""
        compose_path = base / "docker-compose.yml"
        if compose_path.exists():
            existing_compose = compose_path.read_text()

        patch_ctx = f"""
Project: {state.project_name}

EXISTING docker-compose.yml:
{existing_compose}
"""
        patched = self._generate_delimited_files(DOCKER_COMPOSE_PATCH_SYSTEM, patch_ctx)
        for rel_path, content in patched.items():
            try:
                fp = base / rel_path
                fp.parent.mkdir(parents=True, exist_ok=True)
                fp.write_text(content, encoding="utf-8")
            except Exception as exc:
                self.log(f"Warning: could not patch {rel_path}: {exc}")

        total = written + len(patched)
        self.last_summary = (
            f"{written} React/TS files | package.json, vite.config, "
            f"auth, pages, components, API hooks"
        )
        self.last_output_path = str(base / "frontend")
        self.log(self.last_summary)
        return state
