"""
Deploy Executor
───────────────
Central entry point called from the UI Deploy page.
Routes to the right deployer based on cloud provider,
loading credentials automatically from credentials.json.
"""
from __future__ import annotations
import re
from pathlib import Path
from typing import Callable, Optional
from config.settings import settings
from config.credentials import load_credentials
from .base import check_tool, prerequisite_check, DeployError


LogCallback = Callable[[str], None]


# ── Prerequisite definitions per provider ─────────────────────────────────────

PREREQUISITES: dict[str, list[str]] = {
    "localhost": ["docker"],
    "gcp":       ["docker", "gcloud", "terraform"],
    "aws":       ["docker", "aws", "terraform"],
    "azure":     ["docker", "az", "terraform"],
    "github":    ["git"],
}


def check_prerequisites(provider: str) -> dict[str, bool]:
    return prerequisite_check(PREREQUISITES.get(provider, []))


def _safe_name(name: str) -> str:
    return re.sub(r"[^\w\-]", "_", name).strip("_").lower()


def get_project_code_path(project_name: str) -> Path:
    """Return the root output folder for a given project."""
    safe = _safe_name(project_name)
    return Path(settings.outputs_dir) / safe


def deploy(
    project_name: str,
    provider: str,
    log_cb: Optional[LogCallback] = None,
    use_terraform: bool = False,
) -> str:
    """
    Deploy the generated code for `project_name` to `provider`.
    Returns the deployed URL on success.
    """
    log = log_cb or print
    creds = load_credentials()
    code_path = get_project_code_path(project_name)
    app_name = _safe_name(project_name).replace("_", "-")

    if not code_path.exists():
        raise DeployError(
            f"No output folder found for project '{project_name}'. "
            f"Run the pipeline first to generate code."
        )

    log(f"📂 Project output folder: {code_path}")
    log(f"🎯 Deploying to: {provider.upper()}")
    log("─" * 50)

    if provider == "localhost":
        from . import localhost
        # Look for code in outputs/project/code/ first, then project root
        code_dir = code_path / "code"
        if not code_dir.exists() or not any(code_dir.rglob("docker-compose.yml")):
            code_dir = code_path
        return localhost.deploy(code_dir, log_cb=log_cb)

    elif provider == "gcp":
        from . import gcp
        g = creds.gcp
        code_dir = code_path / "code"
        if not code_dir.exists():
            code_dir = code_path
        return gcp.deploy(
            code_path=code_dir,
            project_id=g.project_id,
            region=g.region,
            service_account_json=g.service_account_json,
            artifact_registry=g.artifact_registry,
            app_name=app_name,
            use_terraform=use_terraform,
            log_cb=log_cb,
        )

    elif provider == "aws":
        from . import aws
        a = creds.aws
        code_dir = code_path / "code"
        if not code_dir.exists():
            code_dir = code_path
        return aws.deploy(
            code_path=code_dir,
            access_key_id=a.access_key_id,
            secret_access_key=a.secret_access_key,
            region=a.region,
            account_id=a.account_id,
            app_name=app_name,
            use_terraform=use_terraform,
            log_cb=log_cb,
        )

    elif provider == "azure":
        from . import azure
        az = creds.azure
        code_dir = code_path / "code"
        if not code_dir.exists():
            code_dir = code_path
        return azure.deploy(
            code_path=code_dir,
            tenant_id=az.tenant_id,
            client_id=az.client_id,
            client_secret=az.client_secret,
            subscription_id=az.subscription_id,
            resource_group=az.resource_group or f"{app_name}-rg",
            location=az.location,
            app_name=app_name,
            use_terraform=use_terraform,
            log_cb=log_cb,
        )

    else:
        raise DeployError(f"Unknown provider: {provider}")


def push_to_github(
    project_name: str,
    log_cb: Optional[LogCallback] = None,
    branch: str = "main",
) -> str:
    """Push entire project output folder to GitHub."""
    from . import github
    creds = load_credentials()
    gh = creds.github
    code_path = get_project_code_path(project_name)
    return github.push(
        code_path=code_path,
        token=gh.token,
        username=gh.username,
        repo_url=gh.repo_url,
        branch=branch,
        commit_message=f"Generated by SDLC Pipeline: {project_name}",
        log_cb=log_cb,
    )
